# Generated by Django 3.2.6 on 2021-08-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['created_at']},
        ),
    ]
