# Generated by Django 3.2.6 on 2021-09-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='banner',
            field=models.URLField(blank=True),
        ),
    ]
